decomposer_tokens= {
    "Notre-Dame": ['Notre', 'Dame'], 
    "pâtissier-boulanger": ['pâtissier', 'boulanger'],
    "Sainte-Claire" : ['Sainte', 'Claire'],
    "rond-point" : ['rond', 'point'],
    "arrière-grand-mère": ["arrière", "grand", "mère"],
    "Pointe-à-Pitre": ["Pointe", "à", "Pitre"],
    "quatre-vingt-dix-neuf": ["quatre", "vingt", "dix", "neuf"],
    "Saint-Jean-de-Maurienne" : ['Saint', 'Jean', 'de', 'Maurienne'], 
    "vingt-et-unième": ["vingt", "et", "unième"],
    "quatre-vingt-sept": ["quatre", "vingt","sept"],
    "Alsace-Lorraine" : ['Alsace', 'Lorraine'],
    "soixante-cinq": ['soixante', 'cinq'],
    "cinq-cents": ['cinq', 'cents'],
    "peut-être": ['peut', 'être'],
    "outre-mer": ['outre', 'mer'],
    "vingt-deux": ['vingt', 'deux'],
    "dix-neuf": ['dix', 'neuf'],
    "médico-sociales": ['médico', 'sociales'],
    "dix-huit" : ["dix", "huit"],
    "Proche-Orient": ["Proche", "Orient"],
    "dix-septième": ["dix", "huitième"],
    "vingt-six": ["vingt","six"],
    "belle-mère": ["belle", "mère"],
    "Jean-Paul": ["Jean", "Paul"],
    "enseignants-chercheurs": ["enseignants", "chercheurs"],
    "trente-six": ["trente", "six"],
    "vingt-neuf": ["vingt", "neuf"],
    "Jean-Baptiste": ["Jean", "Baptiste"],
    "après-midi": ["après", "midi"],
    "Jean-François": ["Jean", "François"],
    "elle-même": ["elle", "même"], 
    "rendez-vous": ["rendez", "vous"],
    "centre-ville": ["centre", "ville"]
    
}